name: Resolve Issue with LLMOps Resolver

on:
  issues:
    types: [labeled]

jobs:
  call-llmops-resolver:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    if: ${{ github.event.label.name == 'assigned-to-llmops-issue-resolver' }} 
    uses: Freelunch-AI/llmops-issue-resolver/.github/workflows/llmops-issue-resolver.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      repository_name: ${{ github.repository }}
    secrets:
      LLMOPS_ISSUE_RESOLVER_APP_ID: ${{ secrets.LLMOPS_ISSUE_RESOLVER_APP_ID }}
      LLMOPS_ISSUE_RESOLVER_APP_PRIVATE_KEY: ${{ secrets.LLMOPS_ISSUE_RESOLVER_APP_PRIVATE_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}